In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Sales_Test_Dataset_INVQR_DBD.csv")
data.head()

A   B   C  D   E
0  10   8   4  5   9
1  20  11   1  4   4
2  14  16  19  8   9
3  10   2   8  5   8
4   8   4  13  8  13

In [3]:
A = list(data['A'])
B = list(data['B'])
C = list(data['C'])
D = list(data['D'])
E = list(data['E'])

In [4]:
print(A[:10])

[10, 20, 14, 10, 8, 6, 9, 8, 11, 26]


In [5]:
def split_sequence(sequence,n_steps):
    X,y = list(),list()
    for i in range(len(sequence)):
        end_ix = i+n_steps
        if end_ix>len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [6]:
n_steps = 7
X, y = split_sequence(A,n_steps)
for i in range(7):
    print(X[i],y[i])

[10 20 14 10  8  6  9] 8
[20 14 10  8  6  9  8] 11
[14 10  8  6  9  8 11] 26
[10  8  6  9  8 11 26] 29
[ 8  6  9  8 11 26 29] 11
[ 6  9  8 11 26 29 11] 1
[ 9  8 11 26 29 11  1] 18


In [7]:
# univariate lstm testing
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [8]:
model.fit(X, y, epochs=200, verbose=1)


Epoch 1/200
63/63 [==============================] - 4s 8ms/step - loss: 140.4249
Epoch 2/200
63/63 [==============================] - 1s 8ms/step - loss: 76.6986
Epoch 3/200
63/63 [==============================] - 1s 8ms/step - loss: 77.7491
Epoch 4/200
63/63 [==============================] - 1s 8ms/step - loss: 75.4026
Epoch 5/200
63/63 [==============================] - 1s 8ms/step - loss: 75.8580
Epoch 6/200
63/63 [==============================] - 1s 8ms/step - loss: 75.2855
Epoch 7/200
63/63 [==============================] - 1s 8ms/step - loss: 76.2238
Epoch 8/200
63/63 [==============================] - 1s 8ms/step - loss: 75.6781
Epoch 9/200
63/63 [==============================] - 1s 8ms/step - loss: 75.0895
Epoch 10/200
63/63 [==============================] - 1s 8ms/step - loss: 76.0822
Epoch 11/200
63/63 [==============================] - 1s 8ms/step - loss: 75.4282
Epoch 12/200
63/63 [==============================] - 1s 8ms/step - loss: 75.6353
Epoch 13/200
63/63 [====

In [9]:
x_input = np.array([13,56,12,34,0,6,7])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[53.79273]]


In [10]:
model.save('panel1.h5')

<h2>Panel b</h2>

In [11]:
n_steps = 7
X, y = split_sequence(B,n_steps)
X = X.reshape((X.shape[0], X.shape[1], n_features))
model.fit(X, y, epochs=200, verbose=1)


Epoch 1/200
63/63 [==============================] - 1s 8ms/step - loss: 49.3404
Epoch 2/200
63/63 [==============================] - 1s 8ms/step - loss: 37.3259
Epoch 3/200
63/63 [==============================] - 1s 8ms/step - loss: 35.0096
Epoch 4/200
63/63 [==============================] - 1s 8ms/step - loss: 33.8868
Epoch 5/200
63/63 [==============================] - 1s 8ms/step - loss: 33.1126
Epoch 6/200
63/63 [==============================] - 1s 8ms/step - loss: 32.2346
Epoch 7/200
63/63 [==============================] - 1s 8ms/step - loss: 31.9459
Epoch 8/200
63/63 [==============================] - 1s 9ms/step - loss: 31.1459
Epoch 9/200
63/63 [==============================] - 1s 9ms/step - loss: 30.5669
Epoch 10/200
63/63 [==============================] - 1s 8ms/step - loss: 30.3556
Epoch 11/200
63/63 [==============================] - 1s 8ms/step - loss: 29.6669
Epoch 12/200
63/63 [==============================] - 1s 8ms/step - loss: 29.3645
Epoch 13/200
63/63 [=====

In [12]:
x_input = np.array([13,56,12,34,0,6,7])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)
model.save('panel2.h5')

[[43.275406]]


<h2>Panel C</h2>

In [13]:
n_steps = 7
X, y = split_sequence(C,n_steps)
X = X.reshape((X.shape[0], X.shape[1], n_features))
model.fit(X, y, epochs=200, verbose=1)


Epoch 1/200
63/63 [==============================] - 1s 8ms/step - loss: 357.1367
Epoch 2/200
63/63 [==============================] - 1s 8ms/step - loss: 254.4963
Epoch 3/200
63/63 [==============================] - 1s 8ms/step - loss: 227.3893
Epoch 4/200
63/63 [==============================] - 1s 8ms/step - loss: 214.7958
Epoch 5/200
63/63 [==============================] - 1s 8ms/step - loss: 206.3751
Epoch 6/200
63/63 [==============================] - 1s 8ms/step - loss: 197.9453
Epoch 7/200
63/63 [==============================] - 1s 8ms/step - loss: 192.2823
Epoch 8/200
63/63 [==============================] - 1s 8ms/step - loss: 190.3285
Epoch 9/200
63/63 [==============================] - 1s 8ms/step - loss: 187.3564
Epoch 10/200
63/63 [==============================] - 1s 8ms/step - loss: 184.2001
Epoch 11/200
63/63 [==============================] - 1s 8ms/step - loss: 179.6929
Epoch 12/200
63/63 [==============================] - 1s 8ms/step - loss: 172.8096
Epoch 13/200


In [14]:
x_input = np.array([13,56,12,34,0,6,7])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)
model.save('panel3.h5')

[[39.018684]]


<h2>Panel D</h2>

In [15]:
n_steps = 7
X, y = split_sequence(D,n_steps)
X = X.reshape((X.shape[0], X.shape[1], n_features))
model.fit(X, y, epochs=200, verbose=1)


Epoch 1/200
63/63 [==============================] - 1s 8ms/step - loss: 17.7071
Epoch 2/200
63/63 [==============================] - 1s 8ms/step - loss: 10.3590
Epoch 3/200
63/63 [==============================] - 1s 8ms/step - loss: 9.5283
Epoch 4/200
63/63 [==============================] - 1s 8ms/step - loss: 9.1619
Epoch 5/200
63/63 [==============================] - 1s 8ms/step - loss: 8.9046
Epoch 6/200
63/63 [==============================] - 1s 8ms/step - loss: 8.7225
Epoch 7/200
63/63 [==============================] - 1s 8ms/step - loss: 8.5795
Epoch 8/200
63/63 [==============================] - 1s 8ms/step - loss: 8.4934
Epoch 9/200
63/63 [==============================] - 1s 8ms/step - loss: 8.4038
Epoch 10/200
63/63 [==============================] - 1s 8ms/step - loss: 8.3150
Epoch 11/200
63/63 [==============================] - 1s 8ms/step - loss: 8.2446
Epoch 12/200
63/63 [==============================] - 1s 8ms/step - loss: 8.2044
Epoch 13/200
63/63 [===============

In [16]:
x_input = np.array([13,56,12,34,0,6,7])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)
model.save('panel4.h5')

[[44.070923]]


<h2>Panel E</h2>

In [17]:
n_steps = 7
X, y = split_sequence(E,n_steps)
X = X.reshape((X.shape[0], X.shape[1], n_features))
model.fit(X, y, epochs=200, verbose=1)


Epoch 1/200
63/63 [==============================] - 1s 8ms/step - loss: 29.7589
Epoch 2/200
63/63 [==============================] - 1s 8ms/step - loss: 19.3327
Epoch 3/200
63/63 [==============================] - 1s 8ms/step - loss: 18.5765
Epoch 4/200
63/63 [==============================] - 1s 9ms/step - loss: 17.8609
Epoch 5/200
63/63 [==============================] - 1s 9ms/step - loss: 17.3029
Epoch 6/200
63/63 [==============================] - 1s 8ms/step - loss: 16.9110
Epoch 7/200
63/63 [==============================] - 1s 9ms/step - loss: 16.4639
Epoch 8/200
63/63 [==============================] - 1s 9ms/step - loss: 16.3182
Epoch 9/200
63/63 [==============================] - 1s 8ms/step - loss: 15.8019
Epoch 10/200
63/63 [==============================] - 1s 9ms/step - loss: 15.4206
Epoch 11/200
63/63 [==============================] - 1s 9ms/step - loss: 15.0355
Epoch 12/200
63/63 [==============================] - 1s 9ms/step - loss: 14.6580
Epoch 13/200
63/63 [=====

In [18]:
x_input = np.array([13,56,12,34,0,6,7])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)
model.save('panel5.h5')

[[56.890476]]


<h1>Loading and testin</h1>

In [7]:
import pandas as pd
import numpy as np
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from tensorflow import keras


n_steps = 7


def split_sequence(sequence,n_steps):
    X,y = list(),list()
    for i in range(len(sequence)):
        end_ix = i+n_steps
        if end_ix>len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)


n_features = 1

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model1 = Sequential()
model1.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model1.add(Dense(1))
model1.compile(optimizer='adam', loss='mse')
model2 = Sequential()
model2.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model2.add(Dense(1))
model2.compile(optimizer='adam', loss='mse')
model3 = Sequential()
model3.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model3.add(Dense(1))
model3.compile(optimizer='adam', loss='mse')
model4 = Sequential()
model4.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model4.add(Dense(1))
model4.compile(optimizer='adam', loss='mse')

model =keras.models.load_model("panel1")
model1=keras.models.load_model("panel2")
model2=keras.models.load_model("panel3")
model3=keras.models.load_model("panel4")
model4=keras.models.load_model("panel5")



In [9]:
import pandas as pd
import numpy as np
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from tensorflow import keras


n_steps = 7


def split_sequence(sequence,n_steps):
    X,y = list(),list()
    for i in range(len(sequence)):
        end_ix = i+n_steps
        if end_ix>len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

model1 = Sequential()
model1.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model1.add(Dense(1))
model1.compile(optimizer='adam', loss='mse')

model2 = Sequential()
model2.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model2.add(Dense(1))
model2.compile(optimizer='adam', loss='mse')

model3 = Sequential()
model3.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model3.add(Dense(1))
model3.compile(optimizer='adam', loss='mse')

model4 = Sequential()
model4.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model4.add(Dense(1))
model4.compile(optimizer='adam', loss='mse')

model5 = Sequential()
model5.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model5.add(Dense(1))
model5.compile(optimizer='adam', loss='mse')

model1.load_weights("panel1")
model2.load_weights("panel2")
model3.load_weights("panel3")
model4.load_weights("panel4")
model5.load_weights("panel5")

In [11]:
x_input = np.array([13,56,12,34,0,6,7])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model1.predict(x_input, verbose=0)
print(yhat)
yhat = model2.predict(x_input, verbose=0)
print(yhat)
yhat = model3.predict(x_input, verbose=0)
print(yhat)
yhat = model4.predict(x_input, verbose=0)
print(yhat)
yhat = model5.predict(x_input, verbose=0)
print(yhat)

[[39.872494]]
[[27.27347]]
[[28.95097]]
[[37.951763]]
[[12.16875]]
